version: '3'

services:
  neo4j:
    image: neo4j:4.2
    ports:
      - "7474:7474" # for HTTP
      - "7687:7687" # for Bolt
    volumes:
      #- ${HOME}/neo4j/data:/data
      #- ${HOME}/neo4j/logs:/logs
      #- ${HOME}/neo4j/conf:/conf
      - ${HOME}/neo4j/import:/import # CSVインポートをする場合には必要
    environment:
    - NEO4J_AUTH=neo4j/pass

  iris:
    build:
      context: ./iris
    hostname: iris
    command:
      --check-caps false
    ports:
    - "1972:1972"
    - "52773:52773"
    volumes:
    - ./cpf:/irisowner/cpf
    - ./python:/irisowner/python
    environment:
    - ISC_CPF_MERGE_FILE=/irisowner/cpf/merge.cpf
    - TZ=JST-9
